### PR TITLE
Testing for repository smart contracts

### PR DESCRIPTION
**Pull request by idea404**
This PR aims to contribute **unit** and **simulation tests** of the smart contracts in the repository.

### CODE REVIEW

**Comment by njelich** [comment]
I just tested this on an M1 Mac, and added a PR with some QoL additions for running it on M1.

While the sandbox tests seem to work fine, resulting in two passed tests:
```
 ✔ main contract: nft metadata view (13.9s)
 ✔ main contract: nft mint call (17s)
 ```
 
 The testnet tests timeout with no other info.
 
 ```
  ✖ Timed out while running tests

  2 tests were pending in __tests__/basic_flow.ava.ts

  ◌ main contract: nft metadata view
  ◌ main contract: nft mint call
 ```
 
 Any ideas if I'm doing something wrong while testing?

**Comment by idea404** [comment]
> I just tested this on an M1 Mac, and added a PR with some QoL additions for running it on M1.
> 
> While the sandbox tests seem to work fine, resulting in two passed tests:
> 
> ```
>  ✔ main contract: nft metadata view (13.9s)
>  ✔ main contract: nft mint call (17s)
> ```
> 
> The testnet tests timeout with no other info.
> 
> ```
>  ✖ Timed out while running tests
> 
>  2 tests were pending in __tests__/basic_flow.ava.ts
> 
>  ◌ main contract: nft metadata view
>  ◌ main contract: nft mint call
> ```
> 
> Any ideas if I'm doing something wrong while testing?

Hey! Thanks for checking this out! I've managed to fix this issue locally and pushed the updates to the branch. Hopefully works on your machine now too?

**Comment by njelich** [comment]
Just edited the scripts to fix github test runners #26

**Comment by BenKurrek** [comment]
Deprecated

**Pull request closed without merging**
